// demo/vue/src/components/AddTask.vue
<script setup>
import { ref } from 'vue';

defineProps({
  filters: { type: Array, required: true },
  active: { type: String, required: true },
});

const emit = defineEmits(['add', 'filter']);
const text = ref('');

const submit = (e) => {
  e.preventDefault();
  const value = text.value.trim();
  if (!value) return;
  emit('add', value);
  text.value = '';
};
</script>

<template>
  <div class="add-block">
    <form class="add-form" @submit="submit">
      <input
        v-model="text"
        class="add-input"
        placeholder="Add a new task…"
      />
      <button class="btn btn-primary" type="submit">Add</button>
    </form>
    <div class="filters">
      <button
        v-for="name in filters"
        :key="name"
        type="button"
        class="filter-btn"
        :class="{ 'is-active': active === name }"
        @click="emit('filter', name)"
      >
        {{ name }}
      </button>
    </div>
  </div>
</template>

// demo/src/components/AddTask.jsx
import { useState } from 'react';

export function AddTask({ onAdd, filters, active, onFilter }) {
  const [text, setText] = useState('');

  const submit = (e) => {
    e.preventDefault();
    const value = text.trim();
    if (!value) return;
    onAdd(value);
    setText('');
  };

  return (
    <div className="add-block">
      <form className="add-form" onSubmit={submit}>
        <input
          className="add-input"
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Add a new task…"
        />
        <button className="btn btn-primary" type="submit">
          Add
        </button>
      </form>
      <div className="filters">
        {filters.map((name) => (
          <button
            key={name}
            type="button"
            className={`filter-btn ${active === name ? 'is-active' : ''}`}
            onClick={() => onFilter(name)}
          >
            {name}
          </button>
        ))}
      </div>
    </div>
  );
}
