// demo/vue/src/components/TaskItem.vue
<script setup>
defineProps({
  task: { type: Object, required: true },
});
defineEmits(['toggle', 'remove']);
</script>

<template>
  <li class="task" :class="{ 'is-done': task.done }">
    <button
      class="check"
      type="button"
      aria-label="toggle task"
      @click="$emit('toggle', task.id)"
    >
      ✓
    </button>
    <span class="task-text">{{ task.text }}</span>
    <span class="pri" :class="`pri-${task.priority}`">{{ task.priority }}</span>
    <span class="task-tag">#{{ task.tag }}</span>
    <button
      class="task-del"
      type="button"
      aria-label="delete task"
      @click="$emit('remove', task.id)"
    >
      ✕
    </button>
  </li>
</template>

// demo/react/src/components/TaskItem.jsx
export function TaskItem({ task, onToggle, onRemove }) {
  return (
    <li className={`task ${task.done ? 'is-done' : ''}`}>
      <button
        className="check"
        type="button"
        onClick={() => onToggle(task.id)}
        aria-label="toggle task"
      >
        ✓
      </button>
      <span className="task-text">{task.text}</span>
      <span className={`pri pri-${task.priority}`}>{task.priority}</span>
      <span className="task-tag">#{task.tag}</span>
      <button
        className="task-del"
        type="button"
        onClick={() => onRemove(task.id)}
        aria-label="delete task"
      >
        ✕
      </button>
    </li>
  );
}
